// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sinta_asp.Data;

#nullable disable

namespace sinta_asp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115034258_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("sinta_asp.Models.Pendaftaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fakultas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JudulPenelitian")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Jurusan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LokasiPenelitian")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoHp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PathCV")
                        .HasColumnType("longtext");

                    b.Property<string>("PathProposal")
                        .HasColumnType("longtext");

                    b.Property<string>("PathSurat")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TempatLahir")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TglLahir")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TglMulai")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TglSelesai")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Universitas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pendaftarans");
                });
#pragma warning restore 612, 618
        }
    }
}
