// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sinta_asp.Data;

#nullable disable

namespace sinta_asp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            
            modelBuilder.Entity("sinta_asp.Models.Lowongan", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Company").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("ImageUrl").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Region").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Lowongan");
                });

            modelBuilder.Entity("sinta_asp.Models.Pendaftaran", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Company").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Email").HasColumnType("nvarchar(max)");
                    b.Property<string>("Fakultas").HasColumnType("nvarchar(max)");
                    b.Property<string>("Instagram").HasColumnType("nvarchar(max)");
                    b.Property<string>("JudulPenelitian").HasColumnType("nvarchar(max)");
                    b.Property<string>("Jurusan").HasColumnType("nvarchar(max)");
                    b.Property<string>("LokasiPenelitian").HasColumnType("nvarchar(max)");
                    b.Property<string>("Nama").HasColumnType("nvarchar(max)");
                    b.Property<string>("Nim").HasColumnType("nvarchar(max)");
                    b.Property<string>("NoHp").HasColumnType("nvarchar(max)");
                    b.Property<string>("NomorPendaftaran").HasColumnType("nvarchar(max)"); // Prioritas vava4
                    b.Property<string>("PathCV").HasColumnType("nvarchar(max)");
                    b.Property<string>("PathFoto3x4").HasColumnType("nvarchar(max)"); // Prioritas vava4
                    b.Property<string>("PathProposal").HasColumnType("nvarchar(max)");
                    b.Property<string>("PathSurat").HasColumnType("nvarchar(max)");
                    b.Property<string>("Region").HasColumnType("nvarchar(max)");
                    b.Property<string>("Status").HasColumnType("nvarchar(max)");
                    b.Property<string>("TargetJurusan").HasColumnType("nvarchar(max)");
                    b.Property<string>("TargetLokasi").HasColumnType("nvarchar(max)");
                    b.Property<string>("TempatLahir").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("TglLahir").HasColumnType("datetime2");
                    b.Property<DateTime?>("TglMulai").HasColumnType("datetime2");
                    b.Property<DateTime?>("TglSelesai").HasColumnType("datetime2");
                    b.Property<string>("Universitas").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Pendaftarans");
                });
            
            modelBuilder.Entity("sinta_asp.Models.Admin", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Password").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Role").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.HasKey("Id");
                    b.ToTable("Admins");
                });

            modelBuilder.Entity("sinta_asp.Models.Notification", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Message").HasColumnType("nvarchar(max)");
                    b.Property<string>("Title").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}